name: flutter_template
description: A template Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  tuple: ^2.0.0
  dart_sdk:
    git:
      url: https://github.com/tokend/dart-sdk
      ref: dev


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  material: ^1.0.0+2
  #DI and localisation
  get: ^4.3.8

  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  formz: ^0.4.0
  image_picker: ^0.8.4+2
  intl_phone_number_input: ^0.7.0+2

  #Shared preferences
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.1
  flutter_keychain: ^2.0.1
  synchronized: ^3.0.0
  dcache: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_progress_hud: ^2.0.0
  qr_code_scanner: ^0.5.2
  mime: ^1.0.0
  collection: ^1.15.0
  decimal: ^1.3.0
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  dart_numerics: ^0.0.2
  japx: ^2.0.3
  intl: ^0.17.0
  lazy_evaluation: ^1.1.0
  infinite_scroll_pagination: ^3.1.0
  flutter_switch: ^0.3.2
  rxdart: ^0.27.2
  qr_flutter: ^4.0.0
  cached_network_image: ^3.1.0+1
  syncfusion_flutter_charts: ^19.3.53



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
